### PR TITLE
update contracts

### PR DESCRIPTION
**Pull request by furkhat**
Took latest abi configs and regenerated contracts.

### CODE REVIEW

**Comment by ababo** [comment]
@furkhat So we still include auto-generated files into the repo?

**Comment by furkhat** [comment]
@ababo Yes.

**Comment by ababo** [comment]
To expensive to eliminate?

**Comment by furkhat** [comment]
No idea how to do it.

**Comment by sofabeat** [comment]
Currently it's acceptable.

**Pull request merged**
